//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShivaNegar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkSpaceDirectory {
            get {
                return ((string)(this["WorkSpaceDirectory"]));
            }
            set {
                this["WorkSpaceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptionSettings_ShowDialogCaptionFigure {
            get {
                return ((bool)(this["CaptionSettings_ShowDialogCaptionFigure"]));
            }
            set {
                this["CaptionSettings_ShowDialogCaptionFigure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VirastarSettings_IncludeHalfSpaceCorrectionFootnote {
            get {
                return ((bool)(this["VirastarSettings_IncludeHalfSpaceCorrectionFootnote"]));
            }
            set {
                this["VirastarSettings_IncludeHalfSpaceCorrectionFootnote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VirastarSettings_IncludeHalfSpaceCorrectionHeadersFooters {
            get {
                return ((bool)(this["VirastarSettings_IncludeHalfSpaceCorrectionHeadersFooters"]));
            }
            set {
                this["VirastarSettings_IncludeHalfSpaceCorrectionHeadersFooters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VirastarSettings_IncludeHalfSpaceCorrectionSpecialFields {
            get {
                return ((bool)(this["VirastarSettings_IncludeHalfSpaceCorrectionSpecialFields"]));
            }
            set {
                this["VirastarSettings_IncludeHalfSpaceCorrectionSpecialFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VirastarSettings_CreatePoemType {
            get {
                return ((int)(this["VirastarSettings_CreatePoemType"]));
            }
            set {
                this["VirastarSettings_CreatePoemType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VirastarSettings_IncludeChangeDigitCharacters {
            get {
                return ((bool)(this["VirastarSettings_IncludeChangeDigitCharacters"]));
            }
            set {
                this["VirastarSettings_IncludeChangeDigitCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserToken {
            get {
                return ((string)(this["UserToken"]));
            }
            set {
                this["UserToken"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("311")]
        public int VersionNumber {
            get {
                return ((int)(this["VersionNumber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Mobile {
            get {
                return ((string)(this["Mobile"]));
            }
            set {
                this["Mobile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSaveOnClose {
            get {
                return ((bool)(this["AutoSaveOnClose"]));
            }
            set {
                this["AutoSaveOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberUser {
            get {
                return ((bool)(this["RememberUser"]));
            }
            set {
                this["RememberUser"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VersionAddin {
            get {
                return ((int)(this["VersionAddin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VersionTemplate {
            get {
                return ((int)(this["VersionTemplate"]));
            }
        }
    }
}
